project:
  type: website
  # render: # do not render index by default
  #   - "*.qmd"
  #   - "!index.qmd"

website:
  title: "NERVE Lab Data Management"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: guide.qmd
        text: Guide
    tools:
      - icon: github
        menu:
          - text: Data Access
            href: https://github.com/ajbarrows/nerve-data
  sidebar:
  - title: Guide
    style: "docked"
    contents:
      - text: "Guides"
        href: guide.qmd
      - section: "Accessing Data"        
        contents:
          - access_data.qmd
      - section: "Reproducible Analysis"
        contents:
          - starting_projects.qmd
          - using_git.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



