project:
  type: website

website:
  title: "NERVE Lab Data Management"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: guide.qmd
        text: Guide
    tools:
      - icon: github
        menu:
          - text: Data Access
            href: https://github.com/ajbarrows/nerve-data
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



